spring:
  datasource: # H2 DB ??
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # 웹콘솔 사용하도록 설정 (http://localhost:8080/h2-console)
  jpa:
    database: H2
    show-sql: true # Jpa 수행 시 SQL문 로그 출력
    properties:
      hibernate:
        format_sql: true # 쿼리 출력시 포맷 정렬되도록 설정
        ddl-auto=update:
        ddl-auto:
  mvc:
    contentnegotiation:
      favor-path-extension=false:
      favor-parameter=true:
      defaultContentType=application/json: